#! /bin/bash
#
# Simple kubectl plugin which will display some of the topology 
# information from a vsphere cluster, using Govc - the CLI
# that uses the vmware/govmomi (the GO library for the VMware
# vSphere APIs
#
# Author: CJH - 20th Feb 2019
#
######################################################################
#
# This tool requires Govc - https://github.com/vmware/govmomi/releases
#
######################################################################
#
########################################################################
#
# Usage() - give some instructions about how to use tool, including
# requirements and supported arguments
#
########################################################################

usage()
{
	echo
	echo "Usage: kubectl vtopology <arg>"
	echo "  where arg is one of the following:"
	echo "	-e | --hosts"
	echo "	-v | --vms"
	echo "	-k | --k8svms"
	echo "	-n | --networks"
	echo "	-d | --datastores"
	echo "	-a | --all"
	echo "	-h | --help"
	echo
	echo "Note this tool requires VMware GO API CLI - govc"
	echo "It can be found here: https://github.com/vmware/govmomi/releases"
	echo
	exit;
}

########################################################################
#
# This kubectl plugin also requires the following environment variables
# to be set in the .bash_profile of the user running the plugin:
#
# GOVC_URL="URL of vCenter Server of ESXi host"
# GOVC_USERNAME='login of valid vCenter or ESXi user'
# GOVC_PASSWORD='Passwd of valid vCenter or ESXi user'
# GOVC_INSECURE=true
#
export GOVC_URL="https://vcsa-06-b.rainpole.com"
export GOVC_USERNAME='administrator@vsphere.local'
export GOVC_PASSWORD='VMware123.'
export GOVC_INSECURE=true
#
#######################################################################
#
# Parse the arguments before doing anything else
#
#######################################################################
#
#######################################################################
#
# Display Everything...
# Get the path to VMs, Networks, Hosts and Datastores
#
#######################################################################
#
get_all()
{
	echo "*** VMs ..."
	get_vms
	echo
	echo "*** Hosts ..."
	get_hosts
	echo
	echo "*** Datastoress ..."
	get_datastores
	echo
	echo "*** Networks ..."
	get_networks
	echo
	echo "*** Kubernetes VMs ..."
	get_k8svms
	echo
}
#
#######################################################################
#
# Get VMs
#
#######################################################################
#

get_vms()
{
	echo
	DATACENTER=`govc ls`
	
	for i in ${DATACENTER[@]}; do
	
		if [[ $i =~ vm ]]; then
		govc ls $i
		echo
		fi
	done
}

#
#######################################################################
#
# Get Kubernetes VMs
#
#######################################################################
#

get_k8svms()
{
	echo
	DATACENTER=`govc ls`
	
	for i in ${DATACENTER[@]}; do
	
		if [[ $i =~ vm ]]; then

		K8SVMS=`kubectl get nodes -o wide | awk '{print $7}'`

			for j in ${K8SVMS[@]}; do
				if [[ $j =~ EXTERNAL ]]
				then
					echo
					#no-op
				else
#					echo "DEBUG: EXTERNAL IP OF K8s NODE: $j"
					govc vm.info -vm.ip=${j}
					echo
				fi
			done
		fi
	done
}
#
#######################################################################
#
# Get Networks
#
#######################################################################
#

get_networks()
{
	echo
	DATACENTER=`govc ls`
	
	for i in ${DATACENTER[@]}; do
	
		if [[ $i =~ network ]]; then
		govc ls $i
		echo
		fi
	done
}

#
#######################################################################
#
# Get Hosts
#
#######################################################################
#

get_hosts()
{
	echo
	DATACENTER=`govc ls`
	
	for i in ${DATACENTER[@]}; do
	
		if [[ $i =~ host ]]; then
		echo "Cluster ... "
		govc ls $i
		echo
#
# With the cluster, we can now list the hosts and resources
#
		CLUSTER=`govc ls $i`
		echo "Hosts and Resources..."
		govc ls $CLUSTER
		echo
		HOSTSRES=`govc ls $CLUSTER`
			for host in ${HOSTSRES[@]}; do
#			echo "DEBUG: Found $host ..."
			realhost=`echo $host | awk -F/ '{print $5}'`
			if [[ $realhost =~ Resources ]]; then
#				echo "DEBUG: This is resources ... nothing to do"
				echo
			else
				echo "ESXi host $realhost storage info ..."	
				govc host.storage.info -host=${realhost}
				echo
			fi
		done
		fi
	done
}

#
#######################################################################
#
# Get Datastores
#
#######################################################################
#

get_datastores()
{
	echo
	DATACENTER=`govc ls`
	
	for i in ${DATACENTER[@]}; do
	
		if [[ $i =~ datastore ]]; then
#		echo "DEBUG: Datastores ... $i"
		echo
		govc ls $i
		echo
		fi
	done
}

######################################################################
#
# 1. Count arguments. If there are none, throw usage
# 2. Validate arguments. If unrecognised one, throw usage
#
######################################################################

if [[ $# -eq 0 ]]
then
	usage
else
	case $1 in
		-e|--hosts)
			get_hosts
			;;
		-v|--vms)
			get_vms
			;;
		-n|--networks)
			get_networks
			;;
		-d|--datastores)
			get_datastores
			;;
		-k|--k8svms)
			get_k8svms
			;;
		-a|--all)
			get_all
			;;
		-h|--help)
			usage
			;;
		*)
			usage
			;;
	esac
fi

######################################################################
