apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1.1.2"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux,darwin]}
    uri: ./vtopology.tar.gz
    sha256: "d33a8a36eaa60028d8b532b00d3a9b0426d45330906af79f4f7794d6408191b3"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI, kubectl and awk
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get help on the available options.
