apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1.0.5"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
    uri: ./vtopology.tar.gz
    sha256: "7803959d7999d6936e27e3fdeb1403cb283e191e56f1606f3b85f5ecb8be6a1a"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI and kubectl
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get more description and example usages.
