apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1.0.9"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux,darwin]}
    uri: ./vtopology.tar.gz
    sha256: "ce1c51b8385eb90aaf2bd76f1f61c854a2153af4fd30039089aa15f5f9b9afc2"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI, kubectl and awk
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get help on the available options.
