apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1.0.2"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
    uri: ./vtopology.tar.gz
    sha256: "fe3193bb88ca8df2bf579040a8a967c060f1c5bab35324855015f8eac251b1be"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI and kubectl
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get more description and example usages.
