apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1.0.7"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
    uri: ./vtopology.tar.gz
    sha256: "f7b8c979ac98bcba641f5864f3d79be4ae91e370adf30755a8c8464e8ee1d855"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI, kubectl and awk
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get more description and example usages.
