apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: vtopology
spec:
  version: "v1"
  platforms:
  - selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: ./vtopology-ps.sh.tar.gz
    sha256: "49fcdfd591bbd62280a15ab069239e6139a2f5dfa772c2628ed6dcda9e998e54"
    files:
    - from: "/*.ps1"
      to: "."     
    bin: "./vtopology.ps1"
  shortDescription: Prints the vSphere topology
  caveats: |
    This plugin needs the following programs:
    * PowerShell, PowerCLI and kubectl
  description: |
    This plugin shows underlying vSphere infrastructure details
    when Kubernetes is running on vSphere. Use the -h | --help
    option to get more description and example usages.
